title: Benjamin Weiner
description: Management Consulting, Analytics, Machine Learning

linkedin_username: bmweiner
github_username:  bmweiner
twitter_username: bmweiner

email: ben@bmweiner.com

timezone: America/New_York

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      author: Ben

gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-mentions
      
jekyll-mentions: https://github.com
